// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// randMatrixUnif
NumericMatrix randMatrixUnif(NumericMatrix original_mat, long int max_iter);
RcppExport SEXP RPortfolioSimilarity_randMatrixUnif(SEXP original_matSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type original_mat(original_matSEXP);
    Rcpp::traits::input_parameter< long int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(randMatrixUnif(original_mat, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// randMatrixLNorm
NumericMatrix randMatrixLNorm(NumericMatrix original_mat, long int max_iter, double meanl, double sdl);
RcppExport SEXP RPortfolioSimilarity_randMatrixLNorm(SEXP original_matSEXP, SEXP max_iterSEXP, SEXP meanlSEXP, SEXP sdlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type original_mat(original_matSEXP);
    Rcpp::traits::input_parameter< long int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type meanl(meanlSEXP);
    Rcpp::traits::input_parameter< double >::type sdl(sdlSEXP);
    rcpp_result_gen = Rcpp::wrap(randMatrixLNorm(original_mat, max_iter, meanl, sdl));
    return rcpp_result_gen;
END_RCPP
}
// randMatrixGamma
NumericMatrix randMatrixGamma(NumericMatrix original_mat, long int max_iter, double shape, double rate);
RcppExport SEXP RPortfolioSimilarity_randMatrixGamma(SEXP original_matSEXP, SEXP max_iterSEXP, SEXP shapeSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type original_mat(original_matSEXP);
    Rcpp::traits::input_parameter< long int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(randMatrixGamma(original_mat, max_iter, shape, rate));
    return rcpp_result_gen;
END_RCPP
}
// vCosSimilarity
double vCosSimilarity(NumericVector a, NumericVector b);
RcppExport SEXP RPortfolioSimilarity_vCosSimilarity(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(vCosSimilarity(a, b));
    return rcpp_result_gen;
END_RCPP
}
// wtVCosSimilarity
double wtVCosSimilarity(NumericVector a, NumericVector b, NumericVector w);
RcppExport SEXP RPortfolioSimilarity_wtVCosSimilarity(SEXP aSEXP, SEXP bSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(wtVCosSimilarity(a, b, w));
    return rcpp_result_gen;
END_RCPP
}
// mCosSimilarity
NumericMatrix mCosSimilarity(NumericMatrix input_mat);
RcppExport SEXP RPortfolioSimilarity_mCosSimilarity(SEXP input_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input_mat(input_matSEXP);
    rcpp_result_gen = Rcpp::wrap(mCosSimilarity(input_mat));
    return rcpp_result_gen;
END_RCPP
}
// wtMCosSimilarity
NumericMatrix wtMCosSimilarity(NumericMatrix input_mat, NumericVector weights);
RcppExport SEXP RPortfolioSimilarity_wtMCosSimilarity(SEXP input_matSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input_mat(input_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(wtMCosSimilarity(input_mat, weights));
    return rcpp_result_gen;
END_RCPP
}
