// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// resample_matrix
NumericMatrix resample_matrix(NumericMatrix original_mat, long int max_iter);
RcppExport SEXP portfolio_smilarity_resample_matrix(SEXP original_matSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type original_mat(original_matSEXP );
        Rcpp::traits::input_parameter< long int >::type max_iter(max_iterSEXP );
        NumericMatrix __result = resample_matrix(original_mat, max_iter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// resample_matrix_conv
NumericMatrix resample_matrix_conv(NumericMatrix original_mat, long int max_iter);
RcppExport SEXP portfolio_smilarity_resample_matrix_conv(SEXP original_matSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type original_mat(original_matSEXP );
        Rcpp::traits::input_parameter< long int >::type max_iter(max_iterSEXP );
        NumericMatrix __result = resample_matrix_conv(original_mat, max_iter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// cosine_similarity
double cosine_similarity(NumericVector a, NumericVector b);
RcppExport SEXP portfolio_smilarity_cosine_similarity(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP );
        double __result = cosine_similarity(a, b);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// similarity_matrix
NumericMatrix similarity_matrix(NumericMatrix input_mat);
RcppExport SEXP portfolio_smilarity_similarity_matrix(SEXP input_matSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type input_mat(input_matSEXP );
        NumericMatrix __result = similarity_matrix(input_mat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
