# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

randMatrix <- function(original_mat, max_iter) {
    .Call('RPortfolioSimilarity_randMatrix', PACKAGE = 'RPortfolioSimilarity', original_mat, max_iter)
}

cosSimilarity <- function(a, b) {
    .Call('RPortfolioSimilarity_cosSimilarity', PACKAGE = 'RPortfolioSimilarity', a, b)
}

matCosSimilarity <- function(input_mat) {
    .Call('RPortfolioSimilarity_matCosSimilarity', PACKAGE = 'RPortfolioSimilarity', input_mat)
}

